name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Golang Action Docker
        uses: docker://ghcr.io/strongishllama/golang-action-docker:latest
        with:
          example-input: Hello world!
